services:
  ytdlp-nfo-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./download:/downloads
      - ./data:/data
      - pip-cache:/root/.cache/pip
    environment:
      - DATA_DIR=/data
      - MAX_CONCURRENT=3
      - MAX_RETRIES=3
      # - YTDLP_CHANNEL=stable
    restart: unless-stopped

volumes:
  pip-cache:

